#!/bin/sh

START_DIR=`pwd`
BUNDLE_DIR=certificates
CA_NAME=OSG-Test-CA

rm -fr $BUNDLE_DIR
mkdir $BUNDLE_DIR
cd $BUNDLE_DIR

cp ../$CA_NAME.pem .
h1=`openssl x509 -in $CA_NAME.pem -noout -subject_hash`
h2=`openssl x509 -in $CA_NAME.pem -noout -subject_hash_old`

cp ../$CA_NAME.signing_policy .

sed -e "s/xyxyxyxy/$h1/g" ../$CA_NAME.namespaces > $CA_NAME.namespaces

touch $CA_NAME.r0

for h in $h1 $h2; do
    ln -s $CA_NAME.pem $h.0
    ln -s $CA_NAME.signing_policy $h.signing_policy
    ln -s $CA_NAME.namespaces $h.namespaces
    touch $h.r0
done

cd $START_DIR
rm -f osg-test-cert-bundle.tar.bz2
tar cjf osg-test-cert-bundle.tar.bz2 hostcert.pem hostkey.pem $BUNDLE_DIR
tar tvf osg-test-cert-bundle.tar.bz2
