#!/usr/bin/python

import os
import re
import smtplib
import sys

RECIPIENTS = (
    'Brian Lin <blin@cs.wisc.edu>',
    'Carl Edquist <edquist@cs.wisc.edu>',
    'Edgar Fajardo <emfajard@ucsd.edu>',
    'John Hover <jhover@bnl.gov>',
    'Jose Caballero <jcaballero@bnl.gov>',
    'Mat Selmeci <matyas@cs.wisc.edu>',
    'Suchandra Thapa <sthapa@ci.uchicago.edu>',
    'Tim Cartwright <cat@cs.wisc.edu>',
    'Tim Theisen <tim@cs.wisc.edu>'
    )

ANALYSIS_FILENAME = 'analyze-test-run.out'
ERROR_FILENAME = 'analyze-test-run.err'
LABEL_FILENAME = 'run_label'

# Adapted from Mat's aggregator/emailer.py script
def mail_message(subject, message, recipients):
    from_addr = 'OSG Tests <osg-software@opensciencegrid.org>'
    payload = 'Subject: %s\r\n' % (subject)
    payload += 'From: %s\r\n' % (from_addr)
    payload += 'To: %s\r\n' % (', '.join(recipients))
    payload += '\r\n'
    payload += message
    smtp = smtplib.SMTP('wid-service-1.chtc.wisc.edu')
    smtp.sendmail(from_addr, recipients, payload)
    smtp.quit()

# Borrowed from osgtest.library.files.read()
def file_contents(path, as_single_string=False):
    the_file = open(path, 'r')
    if as_single_string:
        contents = the_file.read()
    else:
        contents = the_file.readlines()
    the_file.close()
    return contents

# Get timestamp from containing directory
my_directory = os.path.basename(os.getcwd())
my_timestamp = re.sub(r'^run-', '', my_directory)

message = '''OSG VMU tests: %s
http://vdt.cs.wisc.edu/tests/%s/results.html
http://vdt.cs.wisc.edu/tests/%s/packages.html
https://jira.opensciencegrid.org/browse/SOFTWARE-1996\n\n''' % (file_contents(LABEL_FILENAME, as_single_string=True)
                                                                , my_timestamp, my_timestamp)

if not os.path.exists(ANALYSIS_FILENAME):
    subject = 'OSG VMU test results: FAIL: no %s' % (ANALYSIS_FILENAME)
    message = 'No file %s in %s\n' % (ANALYSIS_FILENAME, os.getcwd())
    mail_message(subject, message, RECIPIENTS)
    sys.exit(0)

if os.path.getsize(ANALYSIS_FILENAME) == 0:
    subject = 'OSG VMU test results: FAIL: empty %s' % (ANALYSIS_FILENAME)
    message = 'Analysis output file %s in %s is empty\n' % (ANALYSIS_FILENAME, os.getcwd())
    if os.path.exists(ERROR_FILENAME) and (os.path.getsize(ERROR_FILENAME) > 0):
        message += '\n' + ERROR_FILENAME + ' contents:\n\n' + file_contents(ERROR_FILENAME, as_single_string=True)
    mail_message(subject, message, RECIPIENTS)
    sys.exit(0)

subject = 'OSG VMU test results: ' + file_contents(LABEL_FILENAME, as_single_string=True).strip()
truncated_subject = subject[:77] + '...' if len(subject) > 80 else subject

for line in file_contents(ANALYSIS_FILENAME):
    message += re.sub(r'\x1b.*?m', '', line)

if os.path.exists(ERROR_FILENAME) and (os.path.getsize(ERROR_FILENAME) > 0):
    message += '\n'
    message += '=' * 75
    message += '\n' + ERROR_FILENAME + ' contents:\n\n' + file_contents(ERROR_FILENAME, as_single_string=True)

mail_message(truncated_subject, message, RECIPIENTS)
