#!/usr/bin/python

import os
import pwd
import re
import smtplib
import socket
import sys

RECIPIENTS = (
    'Tim Cartwright <cat@cs.wisc.edu>',
    'Mat Selmeci <matyas@cs.wisc.edu>',
    'Carl Edquist <edquist@cs.wisc.edu>',
    'Brian Lin <blin@cs.wisc.edu>',
    )

ANALYSIS_FILENAME = 'analyze-test-run.out'
ERROR_FILENAME = 'analyze-test-run.err'

# Adapted from Mat's aggregator/emailer.py script
def mail_message(subject, message, recipients):
    from_addr = 'OSG Tests <osg-software@opensciencegrid.org>'
    payload = 'Subject: %s\r\n' % (subject)
    payload += 'From: %s\r\n' % (from_addr)
    payload += 'To: %s\r\n' % (', '.join(recipients))
    payload += '\r\n'
    payload += message
    smtp = smtplib.SMTP('wid-service-1.chtc.wisc.edu')
    smtp.sendmail(from_addr, recipients, payload)
    smtp.quit()

# Borrowed from osgtest.library.files.read()
def file_contents(path, as_single_string=False):
    the_file = open(path, 'r')
    if as_single_string:
        contents = the_file.read()
    else:
        contents = the_file.readlines()
    the_file.close()
    return contents


message = ''

if not os.path.exists(ANALYSIS_FILENAME):
    subject = 'OSG VMU test results: FAIL: no %s' % (ANALYSIS_FILENAME)
    message = 'No file %s in %s\n' % (ANALYSIS_FILENAME, os.getcwd())
    mail_message(subject, message, RECIPIENTS)
    sys.exit(0)

if os.path.getsize(ANALYSIS_FILENAME) == 0:
    subject = 'OSG VMU test results: FAIL: empty %s' % (ANALYSIS_FILENAME)
    message = 'Analysis output file %s in %s is empty\n' % (ANALYSIS_FILENAME, os.getcwd())
    if os.path.exists(ERROR_FILENAME) and (os.path.getsize(ERROR_FILENAME) > 0):
        message += '\n' + ERROR_FILENAME + ' contents:\n\n' + file_contents(ERROR_FILENAME, as_single_string=True)
    mail_message(subject, message, RECIPIENTS)
    sys.exit(0)

subject = 'OSG VMU test results'

for line in file_contents(ANALYSIS_FILENAME):
    message += re.sub(r'\x1b.*?m', '', line)

if os.path.exists(ERROR_FILENAME) and (os.path.getsize(ERROR_FILENAME) > 0):
    message += '\n'
    message += '=' * 75
    message += ERROR_FILENAME + ' contents:\n\n' + file_contents(ERROR_FILENAME, as_single_string=True)

mail_message(subject, message, RECIPIENTS)
