#!/usr/bin/python

import itertools
import os
import re
import sys
import time

import vmu

def generate_dag_fragment(serial, combo):
    platform, sources, packages = combo
    node_name = 'TestRun' + serial

    priority = 0
    if 'osg-tested-internal' in packages:
        priority = 1

    contents = '\n'
    contents += '# Node %s: %s - %s - %s\n' % (serial, platform, sources, ', '.join(packages))
    contents += 'JOB %s single-test-run.sub\n' % (node_name)
    contents += 'VARS %s serial="%s" platform="%s" jobpriority="%d"\n' % (node_name, serial, platform, priority)
    contents += 'SCRIPT POST %s process-job-output %s $JOBID\n' % (node_name, serial)
    if 'osg-tested-internal' in packages:
        contents += 'PRIORITY %s %d\n' % (node_name, priority)
    return contents

def write_osg_test_configuration(serial, combo, directory):
    _, sources, packages = combo
    base_config = open('osg-test.conf', 'r')
    contents = base_config.read() + '\n' # ensure newline in case user forgets it
    base_config.close()

    sources_parts = re.split(r'\s*;\s*', sources)
    if len(sources_parts) == 3:
        contents += 'testsource = %s\n' % (sources_parts[0])
        _, release_series, repositories = sources_parts
    else:
        release_series, repositories = sources_parts
    repo_parts = re.split(r'\s*>\s*', repositories)
    # Remove osg production from any part of the extra repos string
    extrarepos = re.sub(r'osg\s*,\s*', '', repo_parts[0])
    extrarepos = re.sub(r'[,\s]*osg(?!-)', '', extrarepos)
    # Don't add any extra repos if there aren't any
    if extrarepos:
        contents += 'extrarepos = %s\n' % (extrarepos)
    if len(repo_parts) > 1:
        update_parts = re.split(r'\s*/\s*', repo_parts[1])
        if len(update_parts) == 1:
            contents += 'updaterepos = %s\n' % (update_parts[0])
        else:
            contents += 'updaterelease = %s\n' % (update_parts[0])
            if update_parts[1] != 'osg':
                contents += 'updaterepos = %s\n' % (update_parts[1])
    contents += 'packages = %s\n' % (', '.join(packages))
    contents += 'series = %s\n' % (release_series)
    contents += 'sources = %s\n' % (sources)

    vmu.write_file(contents, os.path.join(directory, 'osg-test-%s.conf' % (serial)))


# ------------------------------------------------------------------------------
# MAIN
# ------------------------------------------------------------------------------

if __name__ == '__main__':

    # Define paths
    script_name = os.path.basename(sys.argv[0])

    # Process command-line arguments
    if len(sys.argv) != 2:
        vmu.die('usage: %s PARAMETER-DIR' % (script_name))
    param_dir = sys.argv[1]
    if not os.path.exists(param_dir):
        vmu.die('%s: parameter directory "%s" does not exist' % (script_name, param_dir))

    run_params = vmu.load_run_params(param_dir)
    vmu.pkg_mapping(run_params) # verify uniqueness of package sets + labels
    
    # Set up test run directory
    test_run_directory = os.getcwd()

    # Start DAG file
    dag_contents = '# osg-test run generated %s\n' % (time.strftime('%Y-%m-%d %H:%M'))
    dag_contents += 'CONFIG inner-dag.config\n'

    # Run parameter sweep
    process = 0
    run_combos = [] # keep track of all combos to remove dupes
    for param_file in run_params:
        packages = []
        for package_set in param_file['packages']:
            if type(package_set) is dict:
                packages.append(package_set.values()[0])
            elif type(package_set) is list:
                packages.append(package_set)
            else:
                vmu.die("Got bad package list: '%s'" % package_set)

        for combo in itertools.product(param_file['platform'], param_file['sources'], packages):
            if combo not in run_combos:
                run_combos.append(combo)
                serial = '%03d' % (process)
                dag_contents += generate_dag_fragment(serial, combo)
                write_osg_test_configuration(serial, combo, test_run_directory)
                process += 1
    vmu.write_file(dag_contents, os.path.join(test_run_directory, 'test-run.dag'))
