#!/bin/bash

# Tool to create interactive KVM images from our VMU images
# Usage: make-interactive-image <VMU image filename> <interactive image filename>
set -o errexit

INPUT_IMG=$1
OUTPUT_IMG=$2

if [ $# -ne 2 ]; then
    echo "Usage: make-interactive-image <VMU image filename> <interactive image filename>"
    exit 1
fi

echo "Copying image..."
cp "$INPUT_IMG" "$OUTPUT_IMG"

echo "Making image interactive..."
TMPFILE=$(mktemp -d)/osg-test.init
cat <<'EOF' > $TMPFILE
#!/bin/sh
exit 0
EOF

virt-copy-in -a "$OUTPUT_IMG" $TMPFILE /etc
rm -r $(dirname $TMPFILE)
