#!/bin/bash

# Tool to create interactive KVM images from our VMU images
# Usage: make-interactive-image <VMU image filename> <interactive image filename>

INPUT_IMG=$1
OUTPUT_IMG=$2

if [ $# -ne 2 ]; then
    echo "Usage: make-interactive-image <VMU image filename> <interactive image filename>"
    exit 1
fi

echo "Copying image..."
cp $1 $2

echo "Making image interactive..."
TMPFILE=$(mktemp -d)/osg-test.init
cat <<'EOF' > $TMPFILE
#!/bin/sh

# Try to set the clock correctly
systemctl stop ntpd
ntpdate -u ntp1.cs.wisc.edu ntp2.cs.wisc.edu ntp3.cs.wisc.edu
systemctl start ntpd
EOF

virt-copy-in -a $OUTPUT_IMG $TMPFILE /etc
rm -r $(dirname $TMPFILE)
