#!/bin/sh

safe_run()
{
    "$@"
    exit_status=$?
    if [[ $exit_status -ne 0 ]]; then
        echo "==> FAILED with exit status $exit_status"
        exit $exit_status
    fi
}

print_help()
{
    echo "help: $0 [-n] <label>"
    echo "Options:"
    echo "    -n"
    echo "       Run as nightly test i.e. immediately submit the DAG after setting up the test run"
    echo '    -h, -help, --help'
    echo "       Print this dialogue"

}

NIGHTLY=0

# Parse options and required label arg
while getopts :nh opt; do
    case $opt in
        n)
            NIGHTLY=1
            ;;
        h)
            print_help
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            print_help
            exit 1
            ;;
    esac
done

shift $(($OPTIND-1)) # Pop options we've already read

if [[ $# -ne 1 ]]; then
    echo "ERROR: Received incorrect number of arguments: $#. Expecting one 'label' argument"
    print_help
    exit 1
fi

LABEL="$1"
TEST_HOME=/osgtest/runs
if [[ ! -d $TEST_HOME ]]; then
    safe_run mkdir -p $TEST_HOME
fi

RUN_DIR_NAME=`date '+run-%Y%m%d-%H%M'`
RUN_DIRECTORY=$TEST_HOME/$RUN_DIR_NAME
echo "Run directory: $RUN_DIRECTORY"

# Make the new run directory
safe_run mkdir $RUN_DIRECTORY

# Check out files to a temporary directory
TEMP_DIR=`mktemp --directory`
GIT_CHECKOUT_DIR=$TEMP_DIR/git-files
safe_run git clone --quiet --depth 1 https://github.com/opensciencegrid/vm-test-runs $GIT_CHECKOUT_DIR

# Copy needed files to the run directory
cd $GIT_CHECKOUT_DIR
safe_run cp -r \
    master-run.dag \
    generate-dag.sub generate-dag parameters.d test-exceptions.yaml component-tags.yaml \
    create-io-images.sub create-io-images \
    run-job osg-test.patch test-changes.patch osg-release.patch single-test-run.sub inner-dag.config \
    process-job-output extract-job-output analyze_job_output.py \
    combine-job-analyses analyze-test-run.sub analyze-test-run email-analysis vmu.py \
    report-job-failures report-job-failures.sub \
    vmu-reporter vmu-report-by-src.sub vmu-report-by-pkg.sub taglib.py \
    upload-job-output upload-job-output.sub \
    $RUN_DIRECTORY/
cp /osgtest/rpms/osg-test-*.rpm $RUN_DIRECTORY/ 2> /dev/null
cd $RUN_DIRECTORY
if [ "x$TEMP_DIR" != 'x' ]; then
    rm -fr "$TEMP_DIR"
fi

if [ $NIGHTLY -eq 1 ]; then
    echo "$LABEL" > $RUN_DIRECTORY/run_label
    condor_submit_dag master-run.dag
else
    echo "$LABEL ($USER)" > $RUN_DIRECTORY/run_label
    echo 'Run tests with:'
    echo "    cd $RUN_DIRECTORY"
    echo '    condor_submit_dag master-run.dag'
    exit 0
fi
