#!/usr/bin/python

import re
import smtplib
import time
import os

RECIPIENTS = ('Brian Lin <blin@cs.wisc.edu>',
              'Tim Cartwright <cat@cs.wisc.edu>')

# Adapted from Tim's email-analysis script, which was adapted from Mat's aggregator/emailer.py script
def mail_message(subject, message, recipients):
    from_addr = 'Tim Cartwright <cat@cs.wisc.edu>'
    payload = 'Subject: %s\r\n' % (subject)
    payload += 'From: %s\r\n' % (from_addr)
    payload += 'To: %s\r\n' % (', '.join(recipients))
    payload += '\r\n'
    payload += message
    smtp = smtplib.SMTP('wid-service-1.chtc.wisc.edu')
    smtp.sendmail(from_addr, recipients, payload)
    smtp.quit()

def parse_job_log(logfile):
    f = open(logfile, 'r')
    job_log = f.read()
    f.close()

    messages = {}

    for m in re.finditer(r'^(007 .*?)^\.\.\.', job_log, re.MULTILINE | re.DOTALL):
        error_lines = m.group(1).split('\n')
        banner_match = re.search(r'^007 \((\d+\.\d+.\d+)\) (.*?) Shadow exception!', error_lines[0].strip())
        job_id, timestamp = banner_match.group(1, 2)
        text_match = re.search(r'Error from slot\d+@(.*?): (.*)', error_lines[1].strip())
        try:
            hostname, message = text_match.group(1, 2)
        except AttributeError:
            # Ignore shadow exceptions that don't follow the 'Error from...' format
            pass
        else:
            event = (job_id, timestamp)
            if messages.has_key(message):
                if messages[message].has_key(hostname):
                    messages[message][hostname].append(event)
                else:
                    messages[message][hostname] = [event]
            else:
                messages[message] = {hostname: [event]}

    return messages

def construct_email(messages):
    body = '''In the OSG VM universe test run today, the following shadow exceptions
occurred. Often, these errors indicate a broken libvirt, dnsmasq, firewall, or
other hypervisor configuration issue.  The counts are total exceptions per
hostname.
'''
        
    for message, failures in messages.items():
        body += "\nFailure: %s\n" % message
        for hostname in failures:
            times = 'times'
            if len(failures[hostname]) == 1:
                times = 'time'
            body += "  * %d %s on %s\n" % (len(failures[hostname]), times, hostname)
                
    body += '''
Have a nice day! (^_^)

-- Tim C.'''

    return body

if __name__ == "__main__":
    f = open('run_label', 'r')
    run_label = f.read()
    f.close()

    # Don't harass infrastructure for manual runs
    if run_label != 'nightly\n':
        print 'Skipping manual run.'
        exit(0)

    failures = parse_job_log('osg-test-cat.log')
    message = construct_email(failures)

    run_time = time.gmtime(os.path.getctime('osg-test-cat.log'))
    run_date = time.strftime('%F', run_time)
    
    mail_message('VM universe machine failures - ' + run_date, message, RECIPIENTS)
