#!/bin/sh

MOUNT_DIR=/mnt/user
INPUT_DIR=$MOUNT_DIR/input
OUTPUT_DIR=$MOUNT_DIR/output
SYSTEM_LOG_DIR=$OUTPUT_DIR/system-files

log_command()
{
    echo '----------------------------------------------------------------------'
    echo `date '+%Y-%m-%d %T'`: "$@"
    "$@"
    exit_status=$?
    if [ $exit_status -ne 0 ]; then
        echo "==> FAILED with exit status $exit_status"
    else
        echo '==> OK'
    fi
    echo
    return $exit_status
}

# Runs command up to given number of tries with exponential backoff.  Maximum
# possible sleep time is ((2 ** ($1 - 1)) - 1) seconds.
run_command_with_retries()
{
    try_count=$1
    shift

    log_command "$@" && return 0

    sleep_time=1
    while [ $try_count -gt 1 ]; do
        log_command sleep $sleep_time
        sleep_time=`expr $sleep_time '*' 2`
        try_count=`expr $try_count - 1`
        log_command "$@" && return 0
    done

    return
}

# Set a hostname
log_command ip addr show eth0
ip_address=`ip addr show eth0 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
echo "$ip_address osg-test.localdomain osg-test" >> /etc/hosts
log_command cat /etc/hosts
log_command hostname
log_command hostname osg-test.localdomain
log_command hostname

# Install CA and host certificates
log_command mkdir -p /etc/grid-security
log_command tar xf $INPUT_DIR/osg-test-cert-bundle.tar.bz2 --directory /etc/grid-security --no-same-owner
log_command find /etc/grid-security -ls

# Install repositories
# See, e.g., https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/YumRepositories
run_command_with_retries 8 rpm --upgrade http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
log_command yum --assumeyes install yum-priorities
log_command sed -i -e 's/^plugins=.*$/plugins=1/' /etc/yum.conf
run_command_with_retries 8 rpm --upgrade http://repo.grid.iu.edu/osg-el6-release-latest.rpm

# Install osg-test
RPM_LOCATION=`ls -1 $INPUT_DIR/osg-test-*.rpm 2>/dev/null | tail -n 1`
if [ "x$RPM_LOCATION" != 'x' ]; then
    log_command rpm --install $RPM_LOCATION
else
    log_command yum --assumeyes --enablerepo=osg-testing install osg-test
fi
log_command rpm --verify osg-test

# Patch osg-test
log_command yum --assumeyes install patch
log_command patch --directory=/usr/sbin --input=$INPUT_DIR/osg-test.patch --strip=0
log_command patch --directory=/usr/lib/python2.6/site-packages --input=$INPUT_DIR/test-changes.patch --strip=0
log_command patch --directory=/etc/yum.repos.d --input=$INPUT_DIR/osg-release.patch --strip=0

# Run osg-test
rpm --query --all > $OUTPUT_DIR/rpm-qa-start.log 2>&1
osg-test --config=$MOUNT_DIR/input/osg-test.conf > $OUTPUT_DIR/osg-test-`date '+%Y%m%d'`.log 2>&1
rpm --query --all > $OUTPUT_DIR/rpm-qa-final.log 2>&1

# Debugging
log_command printenv
log_command mount
log_command cat /proc/net/dev
log_command df -h
log_command ls -lF /etc/sysconfig
log_command ls -lF /etc/sysconfig/network-scripts
log_command hostname
log_command hostname --fqdn
log_command ifconfig -a
log_command ip addr show
log_command rpm --query openssl
log_command openssl version
log_command ls -lF /tmp
log_command find /tmp/cvmfs -ls

# System files
if [ ! -e $SYSTEM_LOG_DIR ]; then
    mkdir $SYSTEM_LOG_DIR
fi
cp -r \
    /etc/hosts \
    /etc/nsswitch.conf \
    /etc/resolv.conf \
    /etc/selinux/config \
    /etc/sysconfig/network-scripts/ifcfg-* \
    /etc/udev/rules.d/70-persistent-net.rules \
    /var/log/bestman2 \
    /var/log/boot.log \
    /var/log/dmesg \
    /var/log/messages \
    /var/log/tomcat6 \
    $SYSTEM_LOG_DIR/
