#!/bin/sh

MOUNT_DIR=/mnt/user
OUTPUT_DIR=$MOUNT_DIR/output
LOGPATH=$OUTPUT_DIR/run-job.log
SYSTEM_LOG_DIR=$OUTPUT_DIR/system-files

log_command()
{
    if [ -s $LOGPATH ]; then
        echo >> $LOGPATH
    fi
    echo '----------------------------------------------------------------------' >> $LOGPATH
    echo `date '+%Y-%m-%d %T'`: "$@" >> $LOGPATH
    "$@" >> $LOGPATH 2>&1
    exit_status=$?
    if [ $exit_status -ne 0 ]; then
        echo "==> FAILED with exit status $exit_status" >> $LOGPATH
    else
        echo '==> OK' >> $LOGPATH
    fi
    return $exit_status
}

# Install repositories
# See, e.g., https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/YumRepositories
log_command rpm --upgrade http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
log_command yum --quiet --assumeyes install yum-priorities
log_command sed -i -e 's/^plugins=.*$/plugins=1/' /etc/yum.conf
log_command rpm --upgrade http://repo.grid.iu.edu/osg-el6-release-latest.rpm

# Install osg-test
log_command yum --quiet --assumeyes --enablerepo=osg-testing install osg-test
log_command rpm --verify osg-test

# Run osg-test
rpm --query --all > $OUTPUT_DIR/rpm-qa-start.log 2>&1
osg-test `cat $MOUNT_DIR/input/options.txt` > $OUTPUT_DIR/osg-test-`date '+%Y%m%d'`.log 2>&1
rpm --query --all > $OUTPUT_DIR/rpm-qa-final.log 2>&1

# Debugging
log_command echo $PATH
log_command hostname
log_command hostname --fqdn
log_command mount
log_command cat /proc/net/dev
log_command cat /proc/sys/kernel/hostname
log_command df -h
log_command ls -lF /etc/sysconfig/network-scripts
log_command /sbin/ifconfig -a
log_command /sbin/ip addr show
log_command rpm --query openssl
log_command openssl version
if [ ! -e $SYSTEM_LOG_DIR ]; then
    mkdir $SYSTEM_LOG_DIR
fi
cp /etc/hosts \
   /etc/nsswitch.conf \
   /etc/resolv.conf \
   /etc/sysconfig/network-scripts/ifcfg-* \
   /etc/udev/rules.d/70-persistent-net.rules \
   /var/log/boot.log \
   /var/log/dmesg \
   /var/log/messages \
   $SYSTEM_LOG_DIR/
