#!/bin/sh

MOUNT_DIR=/mnt/user
INPUT_DIR=$MOUNT_DIR/input
OUTPUT_DIR=$MOUNT_DIR/output
SYSTEM_LOG_DIR=$OUTPUT_DIR/system-files

log_command()
{
    echo '----------------------------------------------------------------------'
    echo `date '+%Y-%m-%d %T'`: "$@"
    "$@"
    exit_status=$?
    if [ $exit_status -ne 0 ]; then
        echo "==> FAILED with exit status $exit_status"
    else
        echo '==> OK'
    fi
    echo
    return $exit_status
}

# Runs command up to given number of tries with exponential backoff.  Maximum
# possible sleep time is ((2 ** ($1 - 1)) - 1) seconds.
run_command_with_retries()
{
    try_count=$1
    shift

    log_command "$@" && return 0

    sleep_time=1
    while [ $try_count -gt 1 ]; do
        log_command sleep $sleep_time
        sleep_time=`expr $sleep_time '*' 2`
        try_count=`expr $try_count - 1`
        log_command "$@" && return 0
    done

    return 1
}

# Figure out OSG release series
osg_series=`grep series $INPUT_DIR/osg-test.conf | sed -e 's/series *= *//'`

# Set variables based on OS major version
os_major_version=`sed -e 's/^[^0-9]*//' -e 's/\..*$//' /etc/redhat-release`
case $os_major_version in
    5 )
        epel_url='http://dl.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm'
        osg_url="http://repo.grid.iu.edu/osg/$osg_series/osg-$osg_series-el5-release-latest.rpm"
        priorities_rpm='yum-priorities'
        python_lib_dir='/usr/lib/python2.4'
        ;;
    6 )
        epel_url='http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm'
        if [ "$osg_series" == "3.3" ]; then
            osg_url="http://repo.grid.iu.edu/osg/3.3/el6/development/x86_64/osg-release-3.3-1.osg33.el6.noarch.rpm"
        else
            osg_url="http://repo.grid.iu.edu/osg/$osg_series/osg-$osg_series-el6-release-latest.rpm"
        fi
        priorities_rpm='yum-plugin-priorities'
        python_lib_dir='/usr/lib/python2.6'
        ;;
    7 )
        epel_url='http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm'
        if [ "$osg_series" == "3.3" ]; then
            osg_url="http://repo.grid.iu.edu/osg/3.3/el7/development/x86_64/osg-release-3.3-1.osg33.el7.noarch.rpm"
        else
            osg_url="http://repo.grid.iu.edu/osg/3.2/el7/development/x86_64/osg-release-3.2-7.osg32.el7.noarch.rpm"
        fi
        priorities_rpm='yum-plugin-priorities'
        python_lib_dir='/usr/lib/python2.7'
        ;;
    * )
        echo "Could not determine OS major version from '$os_major_version'"
        exit 2
        ;;
esac

# Debugging (here, in case of early exit)
log_command cat /etc/creation_date
log_command cat /etc/redhat-release
log_command echo $os_major_version
log_command ip addr show
log_command printenv
log_command mount
log_command cat /proc/net/dev

# Set a hostname
if [[ -n `ip addr | grep eth0` ]]; then
    ip_address=`ip addr show eth0 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
elif [[ -n `ip addr | grep ens3` ]]; then
    ip_address=`ip addr show ens3 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
else
    echo 'Could not find IP address'
    exit 1
fi
echo "$ip_address osg-test.localdomain osg-test" >> /etc/hosts
log_command cat /etc/hosts
log_command cat /etc/host.conf
log_command hostname
log_command hostname osg-test.localdomain
log_command hostname

# Do initial check of gethostbyname()
# log_command yum -y install strace
# log_command strace -s 8192 -v $INPUT_DIR/check-hostname osg-test.localdomain

# Install repositories
# See, e.g., https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/YumRepositories
run_command_with_retries 8 rpm --upgrade $epel_url
if [ $? -ne 0 ]; then
    echo 'Could not install EPEL repository'
    exit 1
fi
run_command_with_retries 8 yum -y install $priorities_rpm
log_command sed -i -e 's/^plugins=.*$/plugins=1/' /etc/yum.conf
run_command_with_retries 8 rpm --upgrade $osg_url
if [ $? -ne 0 ]; then
    echo 'Could not install OSG repository'
    exit 1
fi

# Install osg-test
if [ -f $INPUT_DIR/osg-test-trunk.tar.bz2 ]; then
    tar xf $INPUT_DIR/osg-test-trunk.tar.bz2 --directory /tmp
    cd /tmp/osg-test-trunk
    make install DESTDIR=/
    svn_revision=`cat svn-revision.txt`
    log_command echo "osg-test source: svn trunk@$svn_revision" # For post-run analysis
else
    RPM_LOCATION=`ls -1 $INPUT_DIR/osg-test-*.el$os_major_version.noarch.rpm 2>/dev/null | tail -n 1`
    if [ "x$RPM_LOCATION" != 'x' ]; then
        log_command rpm --install $RPM_LOCATION
        log_command rpm --verify osg-test
        rpm_version=`rpm --query osg-test`
        log_command echo "osg-test source: file $rpm_version" # For post-run analysis
    else
        if [ "$osg_series" == "3.3" ]; then
            run_command_with_retries 8 yum -y --enablerepo=osg-development install osg-test --disablerepo=osg --nogpgcheck
        else
            run_command_with_retries 8 yum -y --enablerepo=osg-testing install osg-test --disablerepo=osg
        fi
        if [ $? -ne 0 ]; then
            echo 'Could not install osg-test'
            exit 1
        fi
        log_command rpm --verify osg-test
        rpm_version=`rpm --query osg-test`
        log_command echo "osg-test source: yum $rpm_version" # For post-run analysis
    fi
fi

# Patch osg-test
log_command yum -y install patch --disablerepo=osg
log_command patch --directory=/usr/sbin --input=$INPUT_DIR/osg-test.patch --strip=0
log_command patch --directory=$python_lib_dir/site-packages --input=$INPUT_DIR/test-changes.patch --strip=0
log_command patch --directory=/etc/yum.repos.d --input=$INPUT_DIR/osg-release.patch --strip=0

# Run osg-test
rpm --query --all > $OUTPUT_DIR/rpm-qa-start.log 2>&1
osg-test --config=$MOUNT_DIR/input/osg-test.conf > $OUTPUT_DIR/osg-test-`date '+%Y%m%d'`.log 2>&1
rpm --query --all > $OUTPUT_DIR/rpm-qa-final.log 2>&1

# Debugging
log_command df -h
log_command ls -lF /etc/sysconfig
log_command ls -lF /etc/sysconfig/network-scripts
log_command hostname
log_command hostname --fqdn
# log_command strace -s 8192 -v $INPUT_DIR/check-hostname osg-test.localdomain
log_command ifconfig -a
log_command ip addr show
log_command rpm --query openssl
log_command openssl version
log_command ls -lF /tmp
log_command find /tmp/cvmfs -ls
log_command find /etc/udev/rules.d -ls
log_command find /var/log -ls

# System files
if [ ! -e $SYSTEM_LOG_DIR ]; then
    mkdir $SYSTEM_LOG_DIR
fi
cp -r \
    /etc/host.conf \
    /etc/hosts \
    /etc/nsswitch.conf \
    /etc/resolv.conf \
    /etc/selinux/config \
    /etc/sysconfig/network-scripts/ifcfg-* \
    /etc/udev/rules.d/70-persistent-net.rules \
    /var/log/bestman2 \
    /var/log/boot.log \
    /var/log/dmesg \
    /var/log/globus \
    /var/log/globus-gatekeeper.log \
    /var/log/gridftp-auth.log \
    /var/log/gridftp.log \
    /var/log/messages \
    /var/log/tomcat[56] \
    /var/log/yum.log \
    $SYSTEM_LOG_DIR/
