#!/usr/bin/python

import re
import os
import string
import itertools
import yaml
import taglib
from taglib import Tag, SubTag


CSS_URI =  "http://vdt.cs.wisc.edu/tests/vmu.css"
m = re.search(r'run-((\d*)-\d*)', os.getcwd())
date = m.group(2)
timestamp = m.group(1)
url_base = "http://vdt.cs.wisc.edu/tests/" + timestamp + "/"
repo_filename = "results.html"
pkg_filename = "packages.html" 
homepage = url_base +  repo_filename
pkg_organized_homepage = url_base + pkg_filename

os_translation = {'centos_5_x86_64':{'dver':5, 'short':'CentOS'},
                  'centos_6_x86_64':{'dver':6, 'short':'CentOS'},
                  'rhel_5_x86_64':{'dver':5, 'short':'Red Hat'},
                  'rhel_6_x86_64':{'dver':6, 'short':'Red Hat'},
                  'sl_5_x86_64':{'dver':5, 'short':'Scientific'},
                  'sl_6_x86_64':{'dver':6, 'short':'Scientific'}}

def create_html_and_table():
    html = taglib.Html(page_title='OSG VMU Automated Test Results', css_link=CSS_URI)
    html.body.append_new_tag('h1').append('OSG VMU Automated Test Results')
    html.body.append_new_tag('h2').append(timestamp)
    table = html.body.append_new_tag('table')

    return html, table

def sort_platforms_by_dver(platforms):
    global num_el5
    global num_el6

    organized_platforms = []
    num_el5 = 0
    for platform in platforms:
        if os_translation[platform]['dver'] == 5:
            organized_platforms.insert(num_el5, platform)
            num_el5 = num_el5 + 1
        else:
            organized_platforms.append(platform)

    num_el6 = len(platforms) - num_el5
    return organized_platforms

def concat_packages(packages):
    for idx, package in enumerate(packages):
        packages[idx] = string.join(package, ', ')

    return packages
    
def read_source_params(test_params):
    """
    Generate source_translation from sources attribute of test_params. Sources can take the following forms:
    '3.1; osg' # 3.1 Release
    '3.2; osg > osg-testing' # 3.2 Release ->  3.2 Testing
    '3.1; osg > 3.2/osg' # 3.1 Release -> 3.2 Release
    'trunk; 3.2; osg-testing' # 3.2 Testing (TRUNK)
    """
    repo_translation = {'osg':'Release', 'osg-testing':'Testing'}
    source_translation = {}
    re_sources = re.compile(r'(trunk)?[; ]*(\d.\d)[; ]*([\w-]*)[> ]*(\d.\d)?\/?([\w-]+)?')
    for source in test_params['sources']:
        result = re.sub(r'\s*>\s*', ' -> ', source)
        result = re.sub(r'osg-testing', 'Testing', result)
        result = re.sub(r'osg', 'Release', result) # Must come after osg-testing
        result = re.sub(r';', '', result)
        result = re.sub(r'/', ' ', result)
        result = re.sub(r'^(\d+\.\d+)(.*-> )(?!\d)', '\\1\\2\\1 ', result) # Duplicate release series, when needed
        result = re.sub(r'^trunk\s*(.*)$', '\\1 (TRUNK)', result)
        source_translation[source] = result
    return source_translation

def make_data_grid(runs, test_params, organization_scheme='repos'):
    num_rows = range(0, len(runs)/len(test_params['platform'])) 
    organized_runs = [[None] * len(test_params['platform']) for i in num_rows] # Create a 2D array to hold the runs
    for run in runs:
        # Find column value in the grid
        for idx, platform in enumerate(test_params['platform']):
            dver_regex = r'[^\d]' + str(os_translation[platform]['dver']) + r'\.'
            if (re.match(os_translation[platform]['short'], run['os_release']) and
                re.search(dver_regex, run['os_release'])):
                column = idx
                break
            
        # Find row value in the grid
        for idx, package in enumerate(test_params['packages']):
            if package == run['param_packages']:
                package_idx = idx
                break

        for idx, repo in enumerate(test_params['sources']):
            if repo == run['param_sources']:
                repo_idx = idx
                break

        if organization_scheme == 'packages':
            row = repo_idx + package_idx * len(test_params['sources'])
        else:
            row = package_idx + repo_idx  * len(test_params['packages'])

        organized_runs[row][column] = run
    return organized_runs

def create_table_headers(table, organization_scheme='repos'):
    if organization_scheme == 'packages':
        sort_link = homepage
        sort_link_text = 'Sort by Release &#9660;'
        first_column_text = 'Parent Package &#9660;'
        second_column_text = 'OSG Release/Upgrade'
    else:
        sort_link = pkg_organized_homepage
        sort_link_text = 'Sort by Package &#9660;'
        first_column_text = 'OSG Release/Upgrade &#9660;'
        second_column_text = 'Parent Package'

    header = table.append_new_tag("thead")
    row_1 = header.append_new_tag("tr")
    th = row_1.append_new_tag("th", rowspan="2", id = 'sort')
    th.append_new_tag('span', id = 'hide_text').append(first_column_text)
    th.append_new_tag('a', href=sort_link, id = 'sort_link').\
        append(sort_link_text) # mouseover text/link
    row_1.append_new_tag("th", rowspan="2").append(second_column_text)

    row_1.append_new_tag("th", colspan=num_el5).append("EL5")
    row_1.append_new_tag("th", colspan=num_el6).append("EL6")

    row_2 = header.append_new_tag("tr")
    for platform in test_params['platform']:
        row_2.append_new_tag("th").append(os_translation[platform]['short'])

    return table

def populate_table_data(table, data, test_params, organization_scheme='repos'):
    source_translation = read_source_params(test_params)
    pkg_translation = {'osg-tested-internal':'Everything',
                       'condor.x86_64, osg-ce-condor, rsv':'Condor',
                       'osg-gridftp, edg-mkgridmap, rsv':'GridFTP',
                       'osg-se-bestman, rsv':'BeStMan',
                       'osg-voms, rsv':'VOMS',
                       'osg-gums, rsv':'GUMS'}

    if organization_scheme == 'packages':
        outer_org = test_params['packages']
        inner_org = test_params['sources']
        outer_translation = pkg_translation
        inner_translation = source_translation
    else:
        outer_org = test_params['sources']
        inner_org = test_params['packages']
        outer_translation = source_translation
        inner_translation = pkg_translation

    tbody = table.append_new_tag('tbody')

    for row_tuple, inner in itertools.izip(enumerate(data), itertools.cycle(inner_org)):
        row_num = row_tuple[0]
        data = row_tuple[1]
        rowspan_size = len(inner_org)
        if row_num % rowspan_size == 0:
            # Every time we finish looping over the inner organization scheme,
            # we need to move onto the next item in the outer organization scheme.
            tbody.append_new_tag('tr').append_new_tag('td', class_ = 'divider')
            trow = tbody.append_new_tag('tr')
            outer = outer_org[row_num/rowspan_size]
            trow.append_new_tag('th', valign='top', rowspan=rowspan_size).append(outer_translation[outer])
        else:
            trow = tbody.append_new_tag('tr')
        trow.append_new_tag('th').append(inner_translation[inner])
        for cell in data:
            trow.append(get_cell_contents(cell))

def get_cell_contents(run):
    run_dir = url_base + run['job_serial']
    osg_test_version = re.sub('yum.*(\d+\.\d+\.\d+-\d+).*', '\\1', run['osg_test_version'])
    
    # Generic info for each run
    mouseover_text = '<b>Hostname</b>: ' + run['host_name'] + '</br>' + \
        '<b>Host IP</b>: ' + run['host_address'] + '</br>' + \
        '<b>Job ID:</b> ' + str(run['job_id']) + '</br>' + \
        '<b>Job Serial</b>: ' + run['job_serial'] + '</br>'

    if run['run_status'] == 0:
        # Info for all runs of osg-test
        mouseover_text = mouseover_text + \
            '<b>Run Dir</b>: ' + run['run_directory'] + '/output-' + run['job_serial'] + '</br>' + \
            '<b>Guest IP</b>: ' + run['guest_address'] + '</br>' + \
            '<b>OSG Test Version</b>: ' + osg_test_version + '</br>' + \
            '<b>Start Time</b>: ' + str(run['start_time']) + '</br>' + \
            '<b>Run Time</b>: ' + str(run['run_time'])
        # and for the failures...
        if run['osg_test_status'] == 'fail' or run['osg_test_status'] == 'cleanup':
            mouseover_text = mouseover_text + '</br><b>Failures:</b>'
            for test in run['tests_messages']:
                filename, test, module, status, msg = test.split('|')
                mouseover_text = mouseover_text + \
                    '</br><b> %s:</b> %s (%s,%s): %s' % (status, test, filename, module, msg)
        mouseover = Tag('span', class_ = 'mouseover').append(mouseover_text)

        # Construct link tag
        success = run['tests_ok']
        skip = run['tests_ok_skip']
        fail =  run['tests_failed'] + run['tests_error'] + run['tests_bad_skip']
        link_location = run_dir + '/osg-test-' + date + '.log'
        if run['osg_test_status'] == 'timeout':
            link = Tag('a', class_='data', href=link_location).extend(('TIMEOUT', mouseover))
        elif run['osg_test_status'] == 'install':
            link = Tag('a', class_='data', href=link_location).extend(('INSTALL', mouseover))
        else:
            link = Tag('a', href=link_location).extend(("%s %s %s" % (success, skip, fail), mouseover))

        # Construct html
        result_class = 'result ' + run['osg_test_status']
        cell_contents = Tag('div', class_ = 'data').append(link)
        return Tag('td', class_ = result_class, align = 'center').append(cell_contents)
    else:
        mouseover_text = mouseover_text + '<b>Run Summary</b>: ' + run['run_summary']
        mouseover = Tag('span', class_ = 'mouseover').append(mouseover_text)
        link_location = run_dir + '/run-job.log'
        link = Tag('a', class_ = 'result die', href = link_location).extend(('DIED', mouseover))
        cell_contents = Tag('div', class_ = 'data').append(link)
        return Tag('td', class_ = 'result die', align = 'center').append(cell_contents)

def print_html_to_file(html, filename):
    f = open(filename, 'w')
    f.write(str(html))
    f.close()

if __name__ == "__main__":
    # setup html objects
    html_repo, table_repo = create_html_and_table()
    html_pkg, table_pkg = create_html_and_table()

    # Read test parameters
    f = open('test-parameters.yaml', 'r')
    yaml_data = f.read()
    f.close()
    test_params = yaml.load(yaml_data)
    test_params['platform'] = sort_platforms_by_dver(test_params['platform'])
    test_params['packages'] = concat_packages(test_params['packages'])

    # Map runs to their rows
    f = open('combined-analysis.yaml', 'r')
    yaml_data = f.read()
    f.close()
    runs = yaml.load(yaml_data)

    # Create and print repo organized html
    repo_organized_runs = make_data_grid(runs, test_params)
    populate_table_data(create_table_headers(table_repo),
                        repo_organized_runs,
                        test_params)
    print_html_to_file(html_repo, repo_filename)
    
    # Create and print pkg organized html
    pkg_organized_runs = make_data_grid(runs, test_params, organization_scheme='packages')
    populate_table_data(create_table_headers(table_pkg, organization_scheme='packages'),
                        pkg_organized_runs,
                        test_params,
                        organization_scheme='packages')
    print_html_to_file(html_pkg, pkg_filename)
