universe                = vm
executable              = osg-test
priority                = $(jobpriority)

vm_type                 = kvm
vm_memory               = 2048
vm_networking           = true
vm_no_output_vm         = false
vm_vnc                  = true
# Most VM jobs complete in less than 2 hours, give them a 2 hour buffer
periodic_hold           = (time() - JobCurrentStartDate > 14400)
periodic_release        = ( (HoldReasonCode == 3) && (NumJobStarts < 3) ) || ( (HoldReasonCode == 6) && regexp("VMGAHP_ERR_INTERNAL", HoldReason) )
# Most VM jobs spend less than 12 hours in the queue
# We can remove jobs since the DAG can handle removed nodes
periodic_remove         = ( (JobStatus == 5) && (HoldReasonCode =?= 3) && (NumJobStarts >= 3) ) || (time() - QDate >  43200)

request_disk            = 8GB
requirements            = ((HasGluster == True) && (HasVirshDefaultNetwork =?= True))

log                     = osg-test.log

should_transfer_files   = YES
transfer_input_files    = file:///mnt/gluster/chtc/VMs/$(platform)_htcondor.dsk,input-image-$(serial).dsk
vm_disk                 = $(platform)_htcondor.dsk:vda:w:raw,input-image-$(serial).dsk:vdb:w:raw
when_to_transfer_output = ON_EXIT
transfer_output_files   = input-image-$(serial).dsk
transfer_output_remaps  = "input-image-$(serial).dsk = result-image-$(serial).dsk"

queue
