universe                = vm
executable              = osg-test
priority                = $(jobpriority)

vm_type                 = kvm
vm_memory               = 2048
vm_networking           = true
vm_no_output_vm         = false
vm_vnc                  = true
# Most VM jobs complete in less than 2 hours, give them a 2 hour buffer
periodic_hold           = (time() - JobCurrentStartDate > 14400)
periodic_release        = ( (HoldReasonCode == 3) && (NumJobStarts < 3) ) || ( (HoldReasonCode == 6) && regexp("VMGAHP_ERR_INTERNAL", HoldReason) )
# Most VM jobs spend less than 12 hours in the queue
# We can remove jobs since the DAG can handle removed nodes
periodic_remove         = ( (JobStatus == 5) && (HoldReasonCode =?= 3) && (NumJobStarts >= 3) ) || (time() - QDate >  43200)

request_disk            = 16GB
# NOTE: Please inform infrastructure of machines in the following list:
+BadMachineList         = "\
 e2455.chtc.wisc.edu,\
 e2456.chtc.wisc.edu,\
 e2457.chtc.wisc.edu,\
 e2461.chtc.wisc.edu,\
 e2462.chtc.wisc.edu,\
 e2463.chtc.wisc.edu,\
 e2465.chtc.wisc.edu,\
 e2466.chtc.wisc.edu,\
 e2467.chtc.wisc.edu,\
 e2468.chtc.wisc.edu,\
 e2469.chtc.wisc.edu,\
 e2470.chtc.wisc.edu,\
 e2471.chtc.wisc.edu,\
 e2472.chtc.wisc.edu,\
 e2473.chtc.wisc.edu,\
 e2474.chtc.wisc.edu,\
 e2475.chtc.wisc.edu,\
 e2476.chtc.wisc.edu,\
 e2477.chtc.wisc.edu,\
 e2478.chtc.wisc.edu,\
 e2479.chtc.wisc.edu,\
 e2480.chtc.wisc.edu,\
 e2481.chtc.wisc.edu,\
 e2482.chtc.wisc.edu,\
 e2483.chtc.wisc.edu,\
 e2485.chtc.wisc.edu,\
 e4028.chtc.wisc.edu,\
 txie-dsigpu4000.chtc.wisc.edu,\
 voyles2000.chtc.wisc.edu,\
"
requirements            = (TARGET.Arch == split("$(platform)",".")[1]) && (TARGET.HasVirshDefaultNetwork == True) && (TARGET.HasCHTCStaging == True) && !StringListMember(TARGET.Machine, MY.BadMachineList)


log                     = osg-test.log

should_transfer_files   = YES
transfer_input_files    = file:///staging/osg-images/$(platform)_htcondor.dsk,input-image-$(serial).qcow2
vm_disk                 = $(platform)_htcondor.dsk:vda:w:raw,input-image-$(serial).qcow2:vdb:w:qcow2
when_to_transfer_output = ON_EXIT
transfer_output_files   = input-image-$(serial).qcow2
transfer_output_remaps  = "input-image-$(serial).qcow2 = result-image-$(serial).qcow2"

queue
