universe                = vm
executable              = osg-test
priority                = $(jobpriority)

vm_type                 = kvm
vm_memory               = 2048
vm_networking           = true
vm_no_output_vm         = false
vm_vnc                  = true
# Most VM jobs complete in less than 2 hours, give them a 2 hour buffer
periodic_hold           = (time() - JobCurrentStartDate > 14400)
periodic_release        = ( (HoldReasonCode == 3) && (NumJobStarts < 3) ) || ( (HoldReasonCode == 6) && regexp("VMGAHP_ERR_INTERNAL", HoldReason) )
# Most VM jobs spend less than 12 hours in the queue
# We can remove jobs since the DAG can handle removed nodes
periodic_remove         = ( (JobStatus == 5) && (HoldReasonCode =?= 3) && (NumJobStarts >= 3) ) || (time() - QDate >  43200)

request_disk            = 8GB
# Avoid machines with common failures:
# e2371, e2387, e326: htcondor-inf #104692
requirements            = (TARGET.HasVirshDefaultNetwork == True) && (TARGET.HasCHTCStaging == True) && \
    (TARGET.Machine != "e2371.chtc.wisc.edu") && \
    (TARGET.Machine != "e2387.chtc.wisc.edu") && \
    (TARGET.Machine !=  "e326.chtc.wisc.edu")

log                     = osg-test.log

should_transfer_files   = YES
transfer_input_files    = file:///staging/osg-images/$(platform)_htcondor.dsk,input-image-$(serial).qcow2
vm_disk                 = $(platform)_htcondor.dsk:vda:w:raw,input-image-$(serial).qcow2:vdb:w:qcow2
when_to_transfer_output = ON_EXIT
transfer_output_files   = input-image-$(serial).qcow2
transfer_output_remaps  = "input-image-$(serial).qcow2 = result-image-$(serial).qcow2"

queue
